from selenium.webdriver.common.by import By

get_list_elements_loc = (By.XPATH, '//td[@class="oe_product"]')
get_price_for_each_card_loc = (By.XPATH, '//span[@class="oe_currency_value"]')
filter_price_loc = (By.XPATH, '(//a[@class="dropdown-toggle btn btn-light"])[2]')
filter_low_to_high_loc = (By.XPATH, '//a[span[contains(text(), "Price - Low to High")]]')
get_price_after_filtered_loc = (By.XPATH, '//span[@class="oe_currency_value"]')
min_value_loc = (By.XPATH, '//span[@class="multirange-min position-absolute opacity-75 opacity-100-hover mt-1"]')
min_value_for_enter_loc = (By.XPATH, '//input[@type="number"]')
elements_loc = (By.XPATH, '//span[@class="oe_currency_value"]')
all_cards_loc = (By.XPATH, '//div[@class="oe_product_image position-relative h-100 flex-grow-0 overflow-hidden"]')
search_field_loc = (By.XPATH, '(//input[@type="search"])[2]')
inner_info_loc = (By.XPATH, '//a[@class="oe_product_image_link d-block h-100 position-relative"]')
text_loc = (By.XPATH, '//p[@class="text-muted my-2"]')
element_loc = (By.XPATH, '//span[@class="fa fa-shopping-cart"]')
btn_go_to_cart_loc = (By.XPATH, '//a[@class="w-100 btn btn-primary"]')